version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: fkrull/multi-python
    steps:
      - checkout
      - python/load-cache
      - restore_cache:
          keys:
            - tox-cache
      - run:
          command: bash download_fixtures.sh && tox
          name: Test onnx2pytorch
          no_output_timeout: 30m
      - python/save-cache
      - save_cache:
          key: tox-cache
          paths:
            - .tox/
            - fixtures/
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - test
